import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Navigation from "./components/navigation";

/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navigation />
        <main>
          {children}
        </main>
        
      </body>
    </html>
  );
}
